### ISSUE TITLE
Research acceptability model

### ISSUE THREAD

**Issue by lukegonis** [bcgov/cloud-pathfinder-business-process#123]
**Describe the issue**

**Which Sprint Priority is this issue related to?**
3. gain better understanding of overall process, from compliance to procurement to get cloud vendors authorized to provide services to Canadian departments and agencies, with objective for assessing viability, acceptability

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
Identify what will need to happen/be delivered for this to be completely done

**Comment by glam-bert** [comment]
@jromero2020 is this still needed?

**Comment by jromero2020** [comment]
I don’t think so.

Sent from my iPhone

On Jul 16, 2020, at 7:59 AM, glam-bert <notifications@github.com<mailto:notifications@github.com>> wrote:


CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


@jromero2020<https://github.com/jromero2020> is this still needed?

**Comment by sid-gov** [comment]
Paul Roberts confirmed that equivalency/acceptability will not be needed for BC to onboard into the GC brokerage.
