### ISSUE TITLE
Understand where cloud guides will be posted

### ISSUE THREAD

**Issue by glam-bert** [bcgov/cloud-pathfinder-business-process#139]
Gain an understanding of where cloud guides should go (Secure Cloud page, DevHub, digital.gov)

Question for Julian and Shea: which cloud guides? what are examples of this material?

**Which Sprint Priority is this issue related to?**
1. Strengthen Team Foundations

**Definition of done**
Identify who makes this decision

**Comment by sheaphillips** [comment]
@glam-bert @ActionAnalytics noting that this is in the Policy Framework sprint and therefore not accounted for in the Tech Implementation sprint capacity calculation.  Do we want to re-prioritize this over items we *did* include in our capacity, or slide into next sprint?  I ask this partially as I don't really have clarity on what this item involves and perhaps it is smaller than the initial estimate, in which case we can likely accommodate without bumping something else.
