### ISSUE TITLE
Develop Initial Managed Cloud Service Blueprint

### ISSUE THREAD

**Issue by paulroberts68** [bcgov/cloud-pathfinder-business-process#145]
Time boxed development of a conceptual end-to-end service blueprint for teams onboarding and using an OCIO Managed Cloud Service for compute, storage and platforms.

DOD:
- Review Data BC service blueprint
- Time boxed iteration of the service blueprint focusing on the front stage of a self-serve model
- Develop costs/capabilities for three implementation models in-house/outsourced/hybrid

**Comment by glam-bert** [comment]
@scayzer can this be broken down to a ticket that can be completed in Sprint 9? Ideally would like to get a draft blueprint for the front end section of the service - the part that needs to be in place for early adopters to onboard at end of Sept.
