### ISSUE TITLE
Secure Admin & Finance support

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder-business-process#147]
**Describe the issue**
Team requires a permanent resource to manage admin and finance work so it doesn't block other team members

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Commitment from another group to provide a resource 
- Resource identified and start date set

**Comment by glam-bert** [comment]
Nouria Boudhane (DPD ADMO) is the current resouce supporting this. ADMO is adding a team member and when that person is on board that person will be the resource supporting.
