### ISSUE TITLE
SPIKE: Determine what the vehicle to formalize the relationship between BC and GC looks like

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder-business-process#151]
**Describe the issue**
BC wants to use the Fed brokerage system to deliver Cloud services for BC.  BC needs to formalize the relationship with Canada through a Memorandum of Understanding (MOU) or a similar vehicle to do so.

We don't know what this vehicle looks like yet so this work is to assess the options and determine what the content of this document needs to be from a legal perspective. 

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
- FOIPPA, T&Cs
- MOU between BC and Feds

**Definition of done**
- Be able to present at end of sprint what the vehicle (e.g. MOU) to formalize the relationship btw the two governments will look like.

**Comment by jromero2020** [comment]
Paul Roberts has taken the lead on the development of the MOU. Ongoing collaboration with LSB and PCT.
