### ISSUE TITLE
Deck for Early Adopter program

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder-business-process#152]
**Describe the issue**
Our stakeholders need to understand what the Early Adopter program is.  We intend to show this to various ministries. This is a tool to assess interest and recruit a pipeline of prospective good quality candidates for the Early Adopter program.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
- See service definition template from Platform Services (Shea has more info)

**Definition of done**
The Deck will define:
- Goal of program
- Eligibility (what a good quality/ideal Early Adopter will look like)
- what they can expect from program
- what they have to commit to be part of the program

**Comment by sheaphillips** [comment]
@jromero2020 Example "Service Definition" that may be a useful reference as you build out the deck:

https://developer.gov.bc.ca/BC-Government-OpenShift-Container-Platform-Service-Definition

There is a blank/template version here: https://github.com/BCDevOps/openshift-wiki/blob/master/docs/OCP/ServiceDefinition.md

We had aspirations to produce a Service Definition Canvas (inspired by Business Model Canvas) as a more consumable form of the Service Definition, along the lines of (note it's in German): 

(https://app.zenhub.com/files/241743103/8290ca86-02c7-4694-b517-246bf7a7fc02/download)

**Comment by jromero2020** [comment]
Deck reviewed by Gen on July 24th and shared in Teams for general input.
