### ISSUE TITLE
Create FAQ 

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder-business-process#153]
**Describe the issue**
Current available cloud offerings are confusing at the moment.  We wish to provide a clear and consistent set of responses across OCIO and other stakeholders who are curious about cloud.  A document to anticipate the general questions we get from Ministries.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
- Stephen Gidden is working with Emily Jones on this already

**Definition of done**
- A Word document that integrates relevant information from various business areas within OCIO/CITZ
- The document is made available in the Teams Communication Channel and Files
- Reviewed by technical members of Cloud Pathfinder

**Comment by ActionAnalytics** [comment]
Publishing the doc in public is not in scope for this sprint and would later work

**Comment by jromero2020** [comment]
First draft circulated among compliance groups (privacy, security and procurement) for input and review. Next will be posted int he collaboration channel on Teams to get input/feedback from other relevant OCIO areas (e.g. ES).

**Comment by glam-bert** [comment]
What is the current status? Is everyone's input included and ready for my review again?

**Comment by emilyjones430** [comment]
Final draft has gone to @glam-bert for review

**Comment by emilyjones430** [comment]
Final drat is with @glam-bert to determine further approval steps prior to publishing online - see issue #208
