### ISSUE TITLE
Creating Content for SO

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder-business-process#161]
BC requires Service Orders (SO) with the CSP Cloud Service Providers.

PCT (Privacy Compliance and Training) and LSB (Legal Services Branch) collaborate to develop the content of the GCFA (Gov of Canada Framework Agreement) amendments that need to be negotiated with the Brokerage vendors.

PCT is requesting the changes in the 1 to 5 key elements.

DOD: 
- Custom legal language (estimated that roughly 1 to 5 key elements must be changed)
- Content ready to transfer to an SO (Service Order)

**Comment by paulroberts68** [comment]
Partially completed. Waiting for PCT to engage with FOIPPA lawyer and then LSB. Moving ticket back into the backlog.
