### ISSUE TITLE
Brief RMB on Cloud Pathfinder work

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder-business-process#162]
The Risk Management Branch needs to be consulted on the GCFA (Gov of Canada Framework Agreement) language because it differs from the GSA (General Services Agreement) template.  

**Definition of done**
1. Connection identified from RMB branch contact (done)
2. Initial conversation about Cloud Pathfinder work, initiate first meeting of many (done)
3. Review GCFA  indemnity and liability terms with LSB for comments
4. Review GCFA indemnity and liability terms with RMB

**Comment by paulroberts68** [comment]
Set appointment for next sprint.
