### ISSUE TITLE
Signal to SSC Exec that BC intends to onboard to GoC Cloud

### ISSUE THREAD

**Issue by glam-bert** [bcgov/cloud-pathfinder-business-process#163]
**Describe the issue**
Draft email for Hayden to send to head of SSC with intention to onboard to GoC brokerage

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
May require GCIO briefing in advance.

**Definition of done**
Hayden sends email prior to vacation

**Comment by paulroberts68** [comment]
Completed. ADM of DPD has communicated to SSC counterpart.
