### ISSUE TITLE
Develop shortlist of Early Adopter projects

### ISSUE THREAD

**Issue by scayzer** [bcgov/cloud-pathfinder-business-process#173]
We've met with several candidates: MoTI, Education, GDX, PSA. More meetings coming up. It will greatly enhance our prospect of a successful start to our Early Adopters Program, if we can soon select the first two EAs and begin working with them.

DOD
1. Selection of best two candidates, most likely to succeed, and help our teams to learn more about working in the cloud.
2. Agreement amongst CP leadership on choice of first two EAs.

**Comment by sheaphillips** [comment]
We need to have technical review on the EA candidates to ensure they are well aligned for success and that we can provide them with assistance/guidance they may need.

**Comment by scayzer** [comment]
Replaced this one with better defined tickets, breaking work into smaller pieces - 2020-08-24.
