### ISSUE TITLE
Plan phased onboarding to CP Early Adopter Program

### ISSUE THREAD

**Issue by scayzer** [bcgov/cloud-pathfinder-business-process#175]
We've met with several candidates: MoTI, Education, GDX, PSA. More meetings coming up. It will greatly enhance our prospect of a successful start to our Early Adopters Program, if we can soon select the first two EAs and begin working with them, also plan our onboarding process for Sep-Dec. We'll recommend a phased approach to onboarding - one or two first, then adding others if and only if we have capacity to do so.

DOD
1. Draft a plan for onboarding:
- Finalize ordered list for EA/Covid-19 teams starting Nov 20th 
- what are the tasks to be done to onboard an Early Adopter, and who will complete each task?
- peer review (at least one).

**Comment by sheaphillips** [comment]
How is lab connected to this?

**Comment by sid-gov** [comment]
Closing this and create a new ticket for follow-up work.
