### ISSUE TITLE
Capital budget request

### ISSUE THREAD

**Issue by paulroberts68** [bcgov/cloud-pathfinder-business-process#178]
Develop a capital budget request for resources that will be used for building the MMP of the MCS.

DOD:
1. Identify resourcing needs for the team.
2. Get template and understand process.
3. Discuss capital ask with DSO.
4. Develop draft submissions (see below for detail).

**Comment by glam-bert** [comment]
Have discussed with Hayden. We need the following:
1. A change request to the existing Platform/Lab capital request for this fiscal - ideally by eoSeptember

_I can provide an example change request as well as the figures we have already submitted in our budget._ 

2. A dollar figure and short description for the capital we will need next fiscal - by September 15 - should be entered into Copperleaf

_I think this can be based on the resources work that has already been done for the operational service. I would expect the amount to be about half of ongoing operations as we will still be in build mode next fiscal and don't think it is realistic to ramp up to full operations on April 1._

3. A concept case for next fiscal's capital (and any out years - maybe one more year) by September 30 - template and examples are in Copperleaf

**Comment by sid-gov** [comment]
@glam-bert Closing this as our part of the work is done. Pls let me know if we need to track something in a follow-up ticket.
