### ISSUE TITLE
PSB GCFA amendments  

### ISSUE THREAD

**Issue by paulroberts68** [bcgov/cloud-pathfinder-business-process#182]
**Describe the Issue**
Procurement Services Branch (PSB) to provide CP and LSB with a written (email) recommendation regarding the acceptability of the GCFA or required contract amendments.

**Definition of Done**
- SO with GCFA amendments or email confirming non necessary

**Comment by sid-gov** [comment]
@ZachWoodward - I moved this to Blocked since there's still prior work to be done in order to start this. Let me know if I'm wrong.

**Comment by glam-bert** [comment]
@sid-gov, I don't think this is blocked. I believe we have verbal confirmation, just need written.

**Comment by sid-gov** [comment]
@paulroberts68 @ZachWoodward - can this be closed?

**Comment by ZachWoodward** [comment]
Resolved.
