### ISSUE TITLE
ISB amendments to GCFA

### ISSUE THREAD

**Issue by paulroberts68** [bcgov/cloud-pathfinder-business-process#183]
**Describe the issue**
ISB to provide CP and LSB with a written (email) recommendation regarding the acceptability of the GCFA or required contract amendments.

**Value to the product/MVP?**

**Which Sprint Priority is this issue related to?**

**Additional context**

**Definition of Done:**
- SO with GCFA amendments or email confirming non necessary

**Comment by bluemel-gov** [comment]
- Set up meeting with ISB management to discuss on Aug 12th

**Comment by bluemel-gov** [comment]
@paulroberts68 There is a bit of review to do for these GCFA Contract documents, Is there a preference/priority to get this done this sprint or next? I am trying to finish up #213 first and get to this afterwards if that's ok?

**Comment by bluemel-gov** [comment]
- Working/review is happening with isb management and paul.
- ETA Friday end of day.

**Comment by bluemel-gov** [comment]
- awaiting ISB management update.

**Comment by sid-gov** [comment]
ISB Management has signed. Closing.

**Comment by sid-gov** [comment]
Closing as this doesn't need to be tracked anymore.
