### ISSUE TITLE
Meet with BCLC to determine what we can learn from their journey to establish Managed Cloud Services

### ISSUE THREAD

**Issue by scayzer** [bcgov/cloud-pathfinder-business-process#197]
**Describe the issue**
We're developing a Service Blueprint for Managed Cloud Services for BC government, based on Service Design and UX research to determine what are the needs and expectations of ministry teams. We anticipate that we'll learn much more about what capabilities are needed, and how they can be developed, as we begin to actually work with ministry teams in the cloud.

BC Lotteries Commission has been on this journey for several years now, with Onica and Deloitte helping them to develop their Managed Cloud Services practice. They are now planning to transform their org (within the next 6-12 months) towards more internal capabilities. There has to be a lot that we can learn by collaborating with them.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- One or two initial meeting(s) conducted with BCLC leadership team (one of whom is currently on vacation);
- 1-2 page document summarizing key opportunities for further collaboration to inform our Service Blueprint;
- Discuss with CP leadership and decide on next steps (how much to invest in further collaboration with BCLC).

**Comment by scayzer** [comment]
Worked with Nathan Klein (AWS) to set an agenda and line up the meeting for after Paul's vacation (ie., Sep 3 or 4, 2020)
Update: meeting now scheduled for Sep 10 @ 1pm.

Meeting held and contact information exchanged. BCLC have shared info on their business case for cloud adoption, based on cost parity and greatly increased agility (speed to build and deploy new online gaming applications at PlayNow.com).

**Comment by ghost** [comment]
Met with BCLC (Craig & Rob) - very informative & agreed to a regular cadence of meetings for us to share & learn from our experiences.

Started the 1-2 pager [document](https://teams.microsoft.com/l/file/41B10483-75D6-42D4-871A-57AAD1618444?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=docx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F01368%2FShared%20Documents%2FGeneral%2FManaged%20Cloud%20Services%20Blueprint%2FBCLC%20Collaboration.docx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F01368&serviceName=teams&threadId=19:79c414cbe8dc41f3b047a00bc455c318@thread.tacv2&groupId=293d2a85-5978-44d6-a2c8-b0d3c5f7e1af) with notes from the session
