### ISSUE TITLE
Understand PHSA Azure service

### ISSUE THREAD

**Issue by glam-bert** [bcgov/cloud-pathfinder-business-process#203]
211Understand the service PHSA is providing for Azure compute and storage to inform our service and guardrails.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Ministry of Health is placing apps on PHSA's Azure tenancy. PHSA has a signed PIA and SOAR/STRA for the platform. We may be able to learn from what they have done/ are doing.

**Definition of done**
- Obtain PIA, STRA, SOAR
- Discuss with ES what their visibility is (gain any understanding that ES may have so we can repurpose)
- If time permits - Meet with PHSA to exchange service models/plans (service blueprints, shared resp models, technical architecture reference model, identity & access management IAM)

**Comment by hromanow** [comment]
Sent email to Health contact to ask for PHSA PIA, STRA, SOAR or contact (may be easiest route). Cc'd Ryan.

**Comment by bluemel-gov** [comment]
- There is a SOAR but it can't be shared atm.
- Emailed Health MISO to ask if it can be shared and setup meeting for knowledge sharing/what we can learn.

**Comment by bluemel-gov** [comment]
@hromanow @ateppin Could you or someone clarify what 'exchange service plans' is meant? like governance? Thx

**Comment by ghost** [comment]
@bluemel-gov - I don't know.  I'm hoping to get more background into this task etc this afternoon.

**Comment by ghost** [comment]
I have an old work colleague in Health who is trying to use the PHSA Azure tenancy.  I've asked for a copy of any documentation (expecting this to be technical architecture) they may have from PHSA.  Will update if/when I can get a copy.

**Comment by hromanow** [comment]
Sent our draft corporate Azure PIA to Pathfinders. The controls are similar to what is in PHSA's PIA.

**Comment by bluemel-gov** [comment]
- have SOAR from Health. Can share with anyone, just ping if interested.

**Comment by ghost** [comment]
Spoke with Hosting.  Yes, they are aware that PHSA have a separate tenancy but have zero visibility into it or details of it.

**Comment by bluemel-gov** [comment]
- Waiting to confirm notes from HLTH MISO before being sent out.

**Comment by bluemel-gov** [comment]
Have SOAR from HLTH, confirming comments from HLTH. Closed security part as complete.

**Comment by bluemel-gov** [comment]
- Confirming with HLTH cloud security schedule being used.

**Comment by sid-gov** [comment]
Privacy part is complete.

**Comment by ghost** [comment]
ES part is complete.  They have zero visibility into PHSA's Azure tenancy.

**Comment by sid-gov** [comment]
@glam-bert - pls reach out to @ateppin for details
