### ISSUE TITLE
Develop themes for findings from UX Workshops

### ISSUE THREAD

**Issue by scayzer** [bcgov/cloud-pathfinder-business-process#205]
**Describe the issue**.
The Early Adopter Program (EAP) presents an opportunity to UX test key aspects of our delivery model for Managed Cloud Services, as represented by our Service Blueprint. We need to analyze the notes from our UX workshops in order to determine the priority requirements and expectations that ministry teams have identified, that can then be UX tested through the EAP.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Identify themes emerging in the notes from the UX workshops, along with some measure of the priorities of each (perhaps based on the number of mentions);
- Develop a graphical representation for sharing with key stakeholders (demonstrating that we are following up on what we've heard from the intended consumers of our service);
- Identify opportunities to UX test aspects of our service that would address the requirements and expectations of ministry teams.
- Peer review, including Product Owner and Portfolio Owner.

**Comment by ghost** [comment]
Brian has already done some work pulling together themes from the UX workshops & Stu has created the following [document](https://teams.microsoft.com/l/file/EC6AD36C-CC8F-4448-B3A0-1C827F9D30F9?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=docx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F01368%2FShared%20Documents%2FGeneral%2FManaged%20Cloud%20Services%20Blueprint%2FUX%20Research%2FUX%20Workshop%20Themes.docx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F01368&serviceName=teams&threadId=19:79c414cbe8dc41f3b047a00bc455c318@thread.tacv2&groupId=293d2a85-5978-44d6-a2c8-b0d3c5f7e1af) on Teams

**Comment by ghost** [comment]
Reviewed UX workshop notes to pull out details representing the top "demands" of OCIO.  Updated [document ](https://teams.microsoft.com/l/file/EC6AD36C-CC8F-4448-B3A0-1C827F9D30F9?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=docx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F01368%2FShared%20Documents%2FGeneral%2FManaged%20Cloud%20Services%20Blueprint%2FUX%20Research%2FUX%20Workshop%20Themes.docx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F01368&serviceName=teams&threadId=19:79c414cbe8dc41f3b047a00bc455c318@thread.tacv2&groupId=293d2a85-5978-44d6-a2c8-b0d3c5f7e1af)on Teams accordingly.
