### ISSUE TITLE
Get signoff for AWS to CSS mapping

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder-business-process#206]
**Describe the issue**

The Cloud Security Schedule (CSS) was an evolutionary outcome of a brick and mortar schedule and may have some gaps with respect Cloud Service Providers.  There is a desire to improve the CSS.  A CSP when signing up must comply with either BC standards or equivalent GC Protected B Medium Medium (PBMM), Fedramp, CSA*, Schedule G.  

Understand the current compliance against cloud security schedule against AWS.  AWS has existing reports, SOC 2 being one of them that may contain helpful security rankings we can map against.

**Value to the product/MVP?**
It would help with onboarding further services to cloud services, including MVP, and any early adoptors.

**Which Sprint Priority is this issue related to?**

**Additional context**

**Definition of Done:**

- Reviewed by Gary Perkins
- Alignment with ISB Management

**Comment by bluemel-gov** [comment]
- This high level work has been completed. and published internally.
