### ISSUE TITLE
FAQ Document Sign-off

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder-business-process#208]
**Describe the issue**
Get input from stakeholders to publish at https://www2.gov.bc.ca/gov/content/governments/services-for-government/secure-cloud

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Reviewed by Privacy, Procurement, Security and GCPE (if needed). 

**Definition of done**
- Reviewed and feedback incorporated (Gen to approve)
- Published at the above website
- Link added to the Teams Wiki

**Comment by sid-gov** [comment]
@glam-bert to begin approval process and loop in @emilyjones430 as needed.

**Comment by emilyjones430** [comment]
FAQs went out for comment to EDs across CITZ for comments and edits. No further feedback was received so FAQs are considered to be approved.
