### ISSUE TITLE
Decision Note - ADM DPDD

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder-business-process#209]
**Describe the issue**
To seek decision note from ADM Digital Platforms and Data Division (DPDD) on accepting the risks as a 3rd party to the contractual relationship between Shared Services Canada (SSC) and Cloud Service Providers (CSP). 

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Reviewed by Executive, Portfolio Owner, Product Owner and Senior Legislative and Policy Analyst
- Decision note sent to ADM DPDD

**Comment by emilyjones430** [comment]
DN went to Hayden first week of September. No further action on this DN/ticket required.
