### ISSUE TITLE
Meet with PHSA about Azure within the scope of future CP MVP work

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder-business-process#211]
Understand the service PHSA is providing for Azure compute and storage to inform our service and guardrails.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Ministry of Health is placing apps on PHSA's Azure tenancy. PHSA has a signed PIA and SOAR/STRA for the platform. We may be able to learn from what they have done/ are doing.

**Definition of done**
- Meet with PHSA to exchange service models/plans (service blueprints, shared resp models, technical architecture reference model, identity & access management IAM)
- Schedule future meetings between ES and PHSA if any findings indicate the needs

**Comment by ghost** [comment]
Initial email sent to PHSA after the intro made by Health.

**Comment by ghost** [comment]
Meeting set for Sept 16, 9:30-10am.

**Comment by ghost** [comment]
Initial call took place today with Micheal & Ben from PHSA as well as Rick from Health.

Great conversation with PHSA, agreement for subsequent meetings & bringing in other folks from their teams & we also volunteered to bring forwards some ES resources.

Prior to the meeting I also spoke separately to ES (Dennis) about a collaboration possibility & he had a positive response.
