### ISSUE TITLE
Include Procurement Privacy Content in Compute and Storage PIA

### ISSUE THREAD

**Issue by hromanow** [bcgov/cloud-pathfinder-business-process#217]
**Describe the issue**
The compute and storage PIA (focusing on AWS) is nearing completion for the draft phase of the process. Content is needed following the outcome of the procurement: whatever privacy terms AWS agrees to will be documented as mitigations to data residency and data sovereignty in the PIA.  

**Which Sprint Priority is this issue related to?**
Sprint 12

**Additional context**
The latest draft of the PIA is on Teams.

**Definition of done**
- AWS agrees to certain privacy terms and signs the Service Order (exact vehicle TBD)
- Holly summarizes the privacy terms as mitigations to data residency and data sovereignty (typically in the Risk Table of the PIA template)

**Comment by hromanow** [comment]
Added placeholder content in the PIA for the potential procurement outcome. Talks with AWS have started.

**Comment by ActionAnalytics** [comment]
Re-estimated higher due to uncertainties

**Comment by hromanow** [comment]
Content updated based on AWS contract. Waiting for procurement to be finalized.
