### ISSUE TITLE
Confirm process/timeline from GoC and AWS

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder-business-process#221]
**Describe the issue**
The project plan needs finalization.  This involves looking at the project plan itself, ensuring that there are no additional steps missing from the document, adding in high-level technology steps and confirming that the timelines are appropriate and achievable.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
- Sid has the existing plan (in teams)

**Definition of done**
- send the project plan to AWS for review & feedback
- send the project plan to GoC for review & feedback
- project plan reviewed by ticket assignees
- any additional steps missing from the document included
- high-level technology steps are included 
- confirmation that the timelines are appropriate and achievable.

**Comment by sid-gov** [comment]
This work is complete.
