### ISSUE TITLE
Walkthrough of GC Cloud service order process for our Legal Services Branch

### ISSUE THREAD

**Issue by scayzer** [bcgov/cloud-pathfinder-business-process#225]
**Describe the issue**
LSB and RMB have concerns about possible implied or explicit commitments that may be made as we begin entering service orders into the GC Cloud Brokering Service CRM system. They've asked for a walkthrough of the process so that they can determine if all is OK or are there concerns that need to be addressed.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
Schedule and conduct a meeting with Paul + LSB + RMB to run through the service order process
Capture notes on the discussion and report to CP leadership

**Comment by ActionAnalytics** [comment]
Park until asked for again

**Comment by scayzer** [comment]
Paul asked again for this for LSB - meeting booked for 3-3:30, Monday, 2020-10-26

**Comment by scayzer** [comment]
Met with Paul, Brendan and Douglas (2020-10-26), ran through service order process, enabling Brendan and Douglas to confirm that there are no implicit or explicit additional commitments for the province embedded therein.
