### ISSUE TITLE
Technical Review of proposed EA Cloud Apps

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder-business-process#241]
**Describe the issue**
This is a sanity check on the technical aspects of each team is proposing to do in AWS and how they will do it involving the three SMEs for them to bring their lens of expertise to the process so that we dont miss any subtle problems. This will come in useful for when teams ask questions to our 3 SMEs because they will have a basic understanding of what they are doing already. 

**Which Sprint Priority is this issue related to?**
1st version of Early Adopter Onboarding and Training

**Additional context**

**Definition of done**
- This is a 1 hour verbal review/virtual meeting 
- Written document for problems that arise (if any)

**Comment by hromanow** [comment]
Another meeting scheduled for next sprint.

**Comment by sid-gov** [comment]
Worked on a flow diagram. Closing this and create new tickets for follow-up work.
