### ISSUE TITLE
Draft Briefing note for procurement (Compute/Storage)

### ISSUE THREAD

**Issue by lukegonis** [bcgov/cloud-pathfinder-business-process#43]
**Describe the issue**

- A clear and concise description of what you want to happen.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**

- Add any other context, attachments or screenshots

**Definition of done**

- initial draft complete, sent to paul
- approval route determined

**Comment by hromanow** [comment]
Draft sent to Paul. 

Need to confirm wording with procurement, security and privacy. Determining due date for that review with Paul.

Legal opinion being sought next week.
