### ISSUE TITLE
Gather list of services for Dynamics PIA

### ISSUE THREAD

**Issue by hromanow** [bcgov/cloud-pathfinder-business-process#45]
**Describe the issue**
Connect with key contacts on Dynamics services being used currently and what services would be useful in the near future. These services will determine the scope of the PIA.

**Which Sprint Priority is this issue related to?**
Not in Peter's list but should be tackled in this sprint

**Additional context**

**Definition of done**
Have a list of services that the Pathfinders group agrees on - for scope of Dynamics

**Comment by ghost** [comment]
I've reached out to MSFT for details about which Dynamics apps/services are: available in Canadian data centers, available based on our "procurement".

I also reached out to the two current clients (EMPR & EDUC) using Dynamics online in the BC Govt tenancy for a copy of their STRA & PIA.

EDUC have sent something which I will share with you & Ryan.
EMPR I spoke with at length this morning & they will send theirs by the end of the week.

**Comment by ghost** [comment]
@hromanow -  I received the following details from Microsoft about the Dynamics online services:

The Dynamics 365 services in Canada are as follows:
•	Customer Service
•	Sales
•	Field Service
•	Marketing
•	Finance
•	Supply Chain Management
•	Commerce
•	Business Central
•	Project Service Automation

Human Resources is currently **NOT** in Canada

They are also checking to see what is covered by our current EA agreement (as I mentioned prior it was just the Customer Engagement bundle - which is all I can currently provision via the Dynamics admin UI)
