### ISSUE TITLE
STRA/SOAR for Azure

### ISSUE THREAD

**Issue by bluemel-gov** [bcgov/cloud-pathfinder-business-process#46]
**Describe the issue**
- Bring compliance for Azure usage up to standards 

**Which Sprint Priority is this issue related to?**

**Additional context**
Add any other context, attachments or screenshots

**  value to the MVP**

**Definition of done**
- Draft reviewed by peers
-Draft submitted for approval/signature
- Scope is for all Azure with AAD sign-on

**Comment by bluemel-gov** [comment]
- worked based on Azure guardrails

**Comment by sid-gov** [comment]
Tech PO says this does not relate to MVP. Closing due to scope.
