### ISSUE TITLE
Contact ADVED - RE: Dynamics Provisioning

### ISSUE THREAD

**Issue by ghost** [bcgov/cloud-pathfinder-business-process#48]
Reach out to Jamie Glennon for possible testing of auto-provision Dynamics instances.

Meeting with Jamie this afternoon.

**Comment by bluemel-gov** [comment]
@ateppin Would be curious what you find out, if you could share. Thanks.

**Comment by ghost** [comment]
Met with Jamie & Andrew from their team.

They do not see a need or a scenario where they would want/need to build & teardown Dynamics instances.  They expect to create instances & not delete them until the lifecycle of their app/project comes to an end.

I shared some links & information with them for possibly provisioning instances & they agreed they could test this for us if we decided we wanted to go further down this road.
