### ISSUE TITLE
High Level Privacy & Security Content for Non-tech Explainer

### ISSUE THREAD

**Issue by ghost** [bcgov/cloud-pathfinder-business-process#61]
**Describe the issue**
High Level Privacy & Security Content for Non-tech Explainer

**Which Sprint Priority is this issue related to?**
Sprint 2

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
Identify what will need to happen/be delivered for this to be completely done

**Comment by hromanow** [comment]
Sent previously created Exec Summary for privacy and cloud to Jenny.
