### ISSUE TITLE
Adding & Reviewing Content for Non-Tech Explainer Doc

### ISSUE THREAD

**Issue by ghost** [bcgov/cloud-pathfinder-business-process#63]
**Describe the issue**
Adding & Reviewing Content for Non-Tech Explainer Doc

**Which Sprint Priority is this issue related to?**
Spring 2

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
Draft document being made available for peer review

**Comment by bluemel-gov** [comment]
- Reviewing Doc.
@hromanow have you had a chance to see/review the DN?

**Comment by bluemel-gov** [comment]
@ateppin anything further needed on this? Might if I ask where this might be published when it's ready?

**Comment by ghost** [comment]
@bluemel-gov - good questions.  Without communications "owning" this I'm not sure where it will be published.  I think we will only be putting it forward in a draft mode, but would defer that decision to @jromero2020.  

I'm also going to add Jenny as an assignee if Zenhub would stop blowing up on me.....

**Comment by jromero2020** [comment]
This doc needs more input and some cleaning. I have been adding some pieces over the last two days but needs more work. Let's aim to have a draft by end of next week (or Wed following the Sprint) so we can discuss with Peter next steps.
