### ISSUE TITLE
On boarding meeting for Jeremy and JP

### ISSUE THREAD

**Issue by jromero2020** [bcgov/cloud-pathfinder-business-process#65]
**Describe the issue**
Initial chat to bring Jeremy Coad and JP Fournier up to speed on the work the cloud pathfinder team is doing and understand Jeremy's and JP's contribution to these efforts. 

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
Meeting attended by Jeremy, JP and a number of cloud pathfinder team folks to discuss current work and priorities and define coordination

**Comment by lukegonis** [comment]
an initial onboarding meeting has occurred, this issue is a continuation of that
