### ISSUE TITLE
Early Adopter Program – Ministries Guideline

### ISSUE THREAD

**Issue by lukegonis** [bcgov/cloud-pathfinder-business-process#88]
**Describe the issue**

**Which Sprint Priority is this issue related to?**
sprint 6 (Stretch goal) Organize early adopter program, aligned with other OCIO initiatives

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
Guideline document approved by Peter and ELT and socialized with MCIOs (this will take more than one sprint)

**Comment by sid-gov** [comment]
Initial draft of guidelines completed and submitted to Peter Watkins for review. Peter, Paul and Jenny discussed with Heather Remacle how to collaborate on onboarding of projects and guidelines.
