### ISSUE TITLE
Non-technical Explainer final draft 

### ISSUE THREAD

**Issue by lukegonis** [bcgov/cloud-pathfinder-business-process#90]
**Describe the issue**

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
Identify what will need to happen/be delivered for this to be completely done

**Comment by sid-gov** [comment]
Final Draft approved by Peter Watkins. Next step was for Peter to discuss with Hayden where/how to distribute the document to relevant stakeholders (eg: MCIOs)
