### ISSUE TITLE
OCIO workshops - Co-creating an end-to-end experience for ordering cloud compute and storage

### ISSUE THREAD

**Issue by paulroberts68** [bcgov/cloud-pathfinder-business-process#98]
related to sprint 6 goal: (Stretch goal) Organize early adopter program, aligned with other OCIO initiatives

Objective: To gather the requirements necessary for ministry development teams to access and use cloud compute and storage so that the OCIO can design and implement an appropriate procurement method. 

- Create UX 1 pager (DONE)
- Design workshops (DONE)
- Present at the MCIO Strategic Council (DONE)
- Recruit participants (Done)

Sprint 10
- Implement workshops 
- Develop initial deck of findings

Sprint 11
- Present back to participants
- Present to OCIO ELT
- Present back to MCIO council

**Comment by glam-bert** [comment]
This needs to be broken down into multiple tickets. @scayzer ideally for each sprint we have a target number of UX sessions to complete and that ticket can be closed at the end of the sprint.

**Comment by scayzer** [comment]
[@glam-bert](https://github.com/glam-bert) - as requested, I've been creating and closing a ticket for each UX session.
